name: 📚 Auto Documentation (Docusaurus)

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.jsx"
      - "**.py"
      - "!docs/**"
      - "!.github/**"
      - "!node_modules/**"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-documentation:
    name: 🤖 Update Documentation
    runs-on: ubuntu-latest

    if: "!contains(github.event.pull_request.title, '[Auto]')"

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🔄 Fetch Base Branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: 🤖 Generate Documentation
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          npx auto-docs generate --base-branch origin/${{ github.event.pull_request.base.ref }}

      - name: 📊 Check Documentation Changes
        id: check_changes
        run: |
          if [[ -n $(git status -s docs/) ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: 💾 Commit Documentation Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git commit -m "docs: auto-update from PR #${{ github.event.pull_request.number }}

          🤖 Generated with Auto-Docs (Docusaurus)
          Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: 📤 Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: git push origin HEAD:${{ github.event.pull_request.head.ref }}

      - name: 💬 Comment on PR
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 📚 Documentation Updated!

              The documentation has been automatically updated based on your code changes.

              🔗 [View Documentation](https://your-docs-url.com)

              ---
              🤖 Generated by Auto-Docs`
            });
